### ISSUE TITLE
Unable to send email if global config does not specify all parameters

### ISSUE THREAD

**Issue by mojimba** [jeffaco/duplicacy-util#12]
This is a minor issue as there is a workaround.

I'm using an internal SMTP server which does not require authentication. So my global config looks like:

```
emailFromAddress: "Duplicacy <duplicacy@company.com>"
emailToAddress: "Systems <systems@company.com>"
emailServerHostname: smtputil.company.com
emailServerPort: 25
emailAuthUsername: 
emailAuthPassword: 
```

Running `duplicacy-util -tm` with the above configuration successfully sends an email out.

However, if I run a backup or other operation and specify `-m`, I get the following error:
```
root@tetlu16util01:~/.duplicacy-util# duplicacy-util -f svn -a -m
13:28:25 Using global config: /root/.duplicacy-util/duplicacy-util.yaml
Error: Unable to send E-Mail; required fields missing from global configuration
```

The workaround I found was to specify a dummy username/password in the file, and thankfully our SMTP server doesn't care about these (I guess gomail library doesn't even send these if they're not requested by the SMTP server):

```
emailAuthUsername: user
emailAuthPassword: pass
```

Updating  the above two lines in the global configuration works for me.

**Comment by jeffaco** [comment]
I'm used to public-facing servers, where its nuts to not use mail authentication.

I modified the code to not require username and password. If the server needs one, it'll just fail during the mail send operation (the remote server will reject the message).

Thanks for your bug report! This will be included in the next release.
