### ISSUE TITLE
No dedicated Command Line Option for "Copy"?

### ISSUE THREAD

**Issue by GH-User** [jeffaco/duplicacy-util#18]
It seems there's no dedicated Command Line Option for "Copy", just a combined one:

> -b Perform duplicacy backup/copy operation

So I can not start a Copy process without a preceding Backup operation?

I want to run Copy without Backup to copy a local storage to a cloud storage. My workaround: I created a "fake" backup with an empty fake folder that runs prior to Copy.

**Comment by jeffaco** [comment]
I didn't think this was necessary when I originally coded this. My reasoning:

A storage isn't just random files, its files created by `duplicacy`. Now, when `duplicacy` originally ran, that's when you'd want to do the copy (so your repository copies are always up to date). It didn't make sense to me to do a backup to a storage and then not immediately follow by a copy operation.

I can add this (it's certainly easy enough), but I'd like to understand your use case a little better. If you're backing up to a local storage (fair enough), wouldn't you want to copy to the remote storage immediately after that? Why wait?

Thanks.

**Comment by GH-User** [comment]
My use case:
1. Backing up various folders from various computers to a combined storage on a different (backup) computer:
– Backup computer PC1 folder ABC to storage XYZcombined on computer X.
– Backup computer PC1 folder DEF to storage XYZcombined on computer X.
– Backup computer PC2 folder XYZ to storage XYZcombined on computer X.
– Backup computer PCXY folder Xxx to storage XYZcombined on computer X.
etc.
2. COPY storage XYZcombined on computer X to cloud storage Backblaze B2.

a) Since this copy process runs on computer X it must run separately and not combined with one of the preceding Backup tasks that are running on the respective computers.

b) The COPY task will run for many weeks because of the limited upload speed. But I need to restart it again and again because unfortunately Duplicacy suddenly stops if Backblaze B2 gives some random error messages and Duplicacy unfortunately doesn't resume the copy process.

**Comment by jeffaco** [comment]
> b) The COPY task will run for many weeks because of the limited upload speed.
> But I need to restart it again and again because unfortunately Duplicacy suddenly
> stops if Backblaze B2 gives some > random error messages and Duplicacy 
> unfortunately doesn't resume the copy process.

I had problems like that with Azure; I reported them and they were fixed. You should open an issue for `duplicacy` and hopefully this would get fixed.

You could also do some fancy filtering of the log and restart `duplicacy-util` if there was an odd error. But this is a hack. Or better yet, if you get meaningful error exit codes from `duplicacy`, then `duplicacy-util` should return those. You could restart if the error code was one of these retry-able errors.

**Comment by jeffaco** [comment]
Resolved in commit 0bd554f59f1436f312341bfd7b1dd6a0c223e41d. Closing this issue.
