### ISSUE TITLE
option to add  -fossils -resurrect to check?

### ISSUE THREAD

**Issue by Ossssip** [jeffaco/duplicacy-util#21]
Hi, @jeffaco, I have just learned about your tool and it works great! Thanks a lot. I have a bunch of suggestions/questions which I will split in separate issues.

The first one is passing additional parameters to `check`. In my environment I have an sftp storage and multitude of clients with not very good connection, and that results in interrupted uploads, so usually I run `prune -exhaustive`, which in turn some times results in chunks fossilized during a revision upload. And that is not an issue, because such chunks are normally restored with `check -fossils -resurrect`. In your tool, however, there are no additional options for `check` command yet, and running it generates a missing chunk error message. Could you please add an option to pass `-fossils -resurrect` to duplicacy while checking?

**Comment by jeffaco** [comment]
I think the best way to handle this is to have a `-quote` feature. A `-quote` feature would allow you to add any "odd-ball" parameters that you wanted, and keeps me out of the business of supporting one-off parameters for an odd request here and there.

For sure, the standard parameters will be supported as they are today. But `-quote` would allow you to add something that was not typical. So, in your example, you might do something like:

```
-quote "-fossels -resurrect"
```

Those would then be added on the command line. I believe that would handle this issue, as well as `prune` with `-exhaustive`.

I'll look at adding this. Or if you'd like, you're welcome to submit a PR for such a capability.

**Comment by jeffaco** [comment]
Implemented "quote" option as discussed in commit f525569. Tested with known flags passed via `quote` (I used `quote: "-threads 8"` for testing). This testing was possible due to reworking of optional flags and how they are supported in `duplicacy-util` via commit dc46049.

Closing this issue. You can build from source to pick this up, or you can wait for the next release of `duplicacy-util`.
