### ISSUE TITLE
option to work with multiple local configs simultaneously

### ISSUE THREAD

**Issue by Ossssip** [jeffaco/duplicacy-util#22]
One one of my clients, I have several different backups running. It would be nice to pass multiple local configs at once to duplicacy-util and to get one email notification in the end. Like
```
duplicacy-util.exe -f config_1 -f config_2 -f config_3
```
instead of
```
duplicacy-util.exe -f config_1
duplicacy-util.exe -f config_2
duplicacy-util.exe -f config_3
```
Is it possible to implement?

**Comment by jeffaco** [comment]
I don't really see much value to this. Normally, I don't see backup logs (except for failures), so I don't care much if I run 1 backup, 3 backups, or 20 backups. I only care about those that fail (and for me, that's highly unusual fortunately - my cloud providers and my internet connection are both very reliable).

Even if I did implement it, it would only make sense to send one mail message per repository anyway (everything is centered around running a backup, that's what's in the log). I could break a message into multiple attachments, one per repository, but it hardly seems worth it (to me anyway). If you really wanted, you could run backups yourself capturing the logs and then send a single E-Mail message to yourself (making sure the subject was marked failure if anything failed). But this rapidly gets "unclear" if, say, a backup gets skipped. Is a skipped backup a success or a failure? Right now, a skipped backup is a skipped backup, and you treat it anyway you'd like.

I'm going to close this. But if you can give me some actual benefit for this feature (other than "it seems kind of nice"), that may help. Right now I just don't see it.
