### ISSUE TITLE
Free Duplicacy GUI is going to Expire , How can i migrate to Duplicacy Cli and use this ? 

### ISSUE THREAD

**Issue by yudhir** [jeffaco/duplicacy-util#41]
I use free Duplicacy GUI and Free Plan on Blackblaze for my small backup needs.

**Comment by jeffaco** [comment]
I'm a fan of supporting `Duplicacy`, even if I'm not using the GUI. I actually have two commercial CLI licenses (more expensive than personal GUI license), just to support the product.

That said: If you want to migrate to the CLI, read the [README.md](https://github.com/jeffaco/duplicacy-util/blob/master/README.md) here. It gives detailed instructions on how to do it, and that's what others have done to start using `duplicacy-util`. If, after trying, you have specific questions, feel free to ask here.

I'll close this issue for now. Feel free to re-open it if you have specific questions, thanks.

**Comment by yudhir** [comment]
My Question is if the util can read the current settings +  backups can continue mostly as is. Or will i have to redo , reupload etc.

**Comment by jeffaco** [comment]
You will need to create two configuration files, a global one and a repository-specific one, as documented in the [README.md](https://github.com/jeffaco/duplicacy-util/blob/master/README.md) file. After that, what you've uploaded already to the cloud will be fine, you won't need to upload again.

Note that `duplicacy-util` does not read in the GUI configuration, you need to create the `duplicacy-util` configuration files yourself. That's not a bad idea, I'd be happy to take a Pull Request to implement that if you felt like contributing.

**Comment by yudhir** [comment]
I don't know Go yet, would be awesome if I could do that. Does GUI even give access to its settings?

**Comment by jeffaco** [comment]
I dunno, I don't use the GUI. I quickly learned that the GUI didn't support what I wanted (backing up the same data to multiple cloud locations for redundancy, etc). As a result, I started with the command line and never looked back. At the time, I was interested in the GUI if it ever got the capabilities I wanted. But at this point I'm so accustomed to the CLI, and the flexibility of the CLI, that I'd never look back.

You had to tell the GUI where to back up to (cloud provider, access keys, etc). That's really all you need to know. And hopefully you recorded that anyway so it should be easy for you to just build `duplicacy-util` configuration files.

I'd suggest that you start with the [README.md](https://github.com/jeffaco/duplicacy-util/blob/master/README.md) file and see if you have questions. If you don't know basic answers (cloud providers, access keys, etc), and you don't know how to get it from the GUI, you'd need to post your questions to `duplicacy` for that. I just don't have familiarity with the GUI to help with that, sorry.

If the README.md file doesn't answer questions on how to use `duplicacy-util`, though, I can help with that.

**Comment by yudhir** [comment]
Okay, I have the configurations saved (keys, location, File Exclusions ). I am sure I can migrate smoothly. 

Bless the 3, 2, 1
