### ISSUE TITLE
2 small things, sample config and excludes

### ISSUE THREAD

**Issue by abclution** [jeffaco/duplicacy-util#46]
Just found this project today, very cool.

A couple of things,

1. An example .yaml config with examples of all options would be super. I know the read me contains most (all?) of the settings but a config to work off of is super helpful.

2. And way to setup excludes for the repository?

Thanks

Edit: I guess using the "quote:" to exclude is possible based on the documentation, I think I answered my own question.

**Comment by jeffaco** [comment]
Hi @abclution Thanks for your suggestions!

1. I have a working [sample configuration](https://github.com/jeffaco/duplicacy-util#local-configuration-file) that gives an "involved" configuration with multiple cloud providers, which I think is easy to pair down to a single cloud provider. Note that that configuration does contain ALL of the settings that I use. When you say "all of the settings", there's a long list, given the `quote:` parameter, but I think most people don't need that. If most people do, I should know about that!<p><p>If you had something else in mind for an example configuration, please do let me know, and I'll look at adding it.

1. By "any way to set up excludes for a repository", I think by this you mean some way to exclude files in a repository? If that's what you mean, this is actually a `duplicacy` question, as the `duplicacy` program controls this, see [Filters/Include exclude patterns](https://forum.duplicacy.com/t/filters-include-exclude-patterns/1089). I'll include a sample `filters` file that I have for one of my repositories here:

```
e:Archive/Distributions/
e:Archive/Software/
e:CloudBackup-NO/
e:CloudBackup-YES/

# Don't back up temporary Mac OS/X files
e:\.DS_Store
e:\.DocumentRevisions-V100/
e:\.apdisk
e:\.fseventsd/
e:\.TemporaryItems/
e:\.Trashes/
e:\.VolumeIcon.icns
```

Hope this helps! If you have further questions, feel free to re-open this issue!
